CI failure handling 1#

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,6 +58,11 @@ jobs:
       - name: expo doctor
         run: npm run doctor
 
+      - name: Intentional failure
+        run: |
+          echo "Testing CI failure handling"
+          exit 1
+
       - name: TypeScript check
         run: npm run typecheck
 
